name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git clone
        id: git_clone
        run: git clone -b "4.5.5" --depth 1 https://github.com/yairm210/Unciv.git

      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: ./Unciv
          push: true
          tags: qyvlik/yairm210-unciv:4.5.5

      -
        name: Build chinese support and push
        id: docker_build_chinese_support_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: qyvlik/yairm210-unciv:4.5.5-chinese
