name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push focal
        id: docker_build_push_focal
        uses: docker/build-push-action@v2
        with:
          build-args: |
            UBUNTU_VERSION=20.04
            UNCIV_TAG=4.6.13
          push: true
          tags: |
            qyvlik/yairm210-unciv:4.6.13
            qyvlik/yairm210-unciv:4.6.13
            qyvlik/yairm210-unciv:latest

      - name: Build and push jammy
        id: docker_build_push_jammy
        uses: docker/build-push-action@v2
        with:
          build-args: |
            UBUNTU_VERSION=latest
            UNCIV_TAG=4.6.13
          push: true
          tags: |
            qyvlik/yairm210-unciv:4.6.13-jammy
